{
 "title": "Cardano: Application metrics grouped",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "role",
    "label": "role",
    "query": "label_values(cardano_chain_quality_overall__,role)"
   }
  ]
 },
 "panels": [
  {
   "title": "Node Stats over all $role",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "role",
   "collapsed": true,
   "panels": [
    {
     "title": "Chain quality (Last k=2160 blocks)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_chain_quality_last_k__2160__blocks__{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Chain Quality Overall",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_chain_quality_overall__{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Chain Quality Last Hour",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_chain_quality_last_3600_sec__{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Queue: Failures",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_queue_Failures{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Bucket Subscription Listener Counts (Total)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_queue_bucket_BucketSubscriptionListener{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Queue: Scheduled",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_queue_Scheduled{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "MemPoolSize",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_MemPoolSize{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "MemPool Modify Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "cardano_MemPoolModifyTimeApplyBlock_microseconds{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - apply block"
      },
      {
       "expr": "cardano_MemPoolModifyTimeProcessTx_microseconds{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - process tx"
      },
      {
       "expr": "cardano_MemPoolModifyTimeApplyBlockWithRollback_microseconds{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - apply block with rollback"
      }
     ]
    },
    {
     "title": "MemPool Wait Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "cardano_MemPoolWaitTimeApplyBlock_microseconds{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - apply block"
      },
      {
       "expr": "cardano_MemPoolWaitTimeProcessTx_microseconds{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - process tx"
      },
      {
       "expr": "cardano_MemPoolWaitTimeApplyBlockWithRollback_microseconds{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - apply block with rollback"
      }
     ]
    },
    {
     "title": "Number of blocks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_total_main_blocks{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Handlers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_handlers_initiated_locally{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - initiated locally"
      },
      {
       "expr": "cardano_handlers_initiated_remotely{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - initiated remotely"
      }
     ]
    },
    {
     "title": "Handlers: Finished Exceptionally",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "cardano_handlers_finished_exceptionally_elapsed_time_microseconds_max{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - max"
      },
      {
       "expr": "cardano_handlers_finished_exceptionally_elapsed_time_microseconds_mean{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - mean"
      }
     ]
    },
    {
     "title": "BucketSubscription (non-stacked)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_queue_bucket_BucketSubscriptionListener{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "BucketSubscription (sum)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (cardano_queue_bucket_BucketSubscriptionListener{role=\"[[role]]\"})",
       "legendFormat": "sum all nodes"
      }
     ]
    },
    {
     "title": "Total Missed Blocks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_current_global_slot - cardano_total_main_blocks{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Stats over all $role",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chain quality (Last k=2160 blocks)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_chain_quality_last_k__2160__blocks__{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Chain Quality Overall",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_chain_quality_overall__{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Chain Quality Last Hour",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_chain_quality_last_3600_sec__{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Queue: Failures",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_queue_Failures{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Bucket Subscription Listener Counts (Total)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_queue_bucket_BucketSubscriptionListener{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Queue: Scheduled",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_queue_Scheduled{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "MemPoolSize",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_MemPoolSize{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "MemPool Modify Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "cardano_MemPoolModifyTimeApplyBlock_microseconds{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - apply block"
      },
      {
       "expr": "cardano_MemPoolModifyTimeProcessTx_microseconds{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - process tx"
      },
      {
       "expr": "cardano_MemPoolModifyTimeApplyBlockWithRollback_microseconds{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - apply block with rollback"
      }
     ]
    },
    {
     "title": "MemPool Wait Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "cardano_MemPoolWaitTimeApplyBlock_microseconds{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - apply block"
      },
      {
       "expr": "cardano_MemPoolWaitTimeProcessTx_microseconds{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - process tx"
      },
      {
       "expr": "cardano_MemPoolWaitTimeApplyBlockWithRollback_microseconds{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - apply block with rollback"
      }
     ]
    },
    {
     "title": "Number of blocks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_total_main_blocks{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Handlers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_handlers_initiated_locally{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - initiated locally"
      },
      {
       "expr": "cardano_handlers_initiated_remotely{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - initiated remotely"
      }
     ]
    },
    {
     "title": "Handlers: Finished Exceptionally",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "cardano_handlers_finished_exceptionally_elapsed_time_microseconds_max{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - max"
      },
      {
       "expr": "cardano_handlers_finished_exceptionally_elapsed_time_microseconds_mean{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - mean"
      }
     ]
    },
    {
     "title": "BucketSubscription (non-stacked)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_queue_bucket_BucketSubscriptionListener{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "BucketSubscription (sum)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (cardano_queue_bucket_BucketSubscriptionListener{role=\"[[role]]\"})",
       "legendFormat": "sum all nodes"
      }
     ]
    },
    {
     "title": "Total Missed Blocks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_current_global_slot - cardano_total_main_blocks{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Stats over all $role",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chain quality (Last k=2160 blocks)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_chain_quality_last_k__2160__blocks__{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Chain Quality Overall",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_chain_quality_overall__{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Chain Quality Last Hour",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_chain_quality_last_3600_sec__{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Queue: Failures",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_queue_Failures{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Bucket Subscription Listener Counts (Total)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_queue_bucket_BucketSubscriptionListener{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Queue: Scheduled",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_queue_Scheduled{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "MemPoolSize",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_MemPoolSize{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "MemPool Modify Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "cardano_MemPoolModifyTimeApplyBlock_microseconds{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - apply block"
      },
      {
       "expr": "cardano_MemPoolModifyTimeProcessTx_microseconds{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - process tx"
      },
      {
       "expr": "cardano_MemPoolModifyTimeApplyBlockWithRollback_microseconds{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - apply block with rollback"
      }
     ]
    },
    {
     "title": "MemPool Wait Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "cardano_MemPoolWaitTimeApplyBlock_microseconds{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - apply block"
      },
      {
       "expr": "cardano_MemPoolWaitTimeProcessTx_microseconds{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - process tx"
      },
      {
       "expr": "cardano_MemPoolWaitTimeApplyBlockWithRollback_microseconds{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - apply block with rollback"
      }
     ]
    },
    {
     "title": "Number of blocks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_total_main_blocks{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Handlers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_handlers_initiated_locally{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - initiated locally"
      },
      {
       "expr": "cardano_handlers_initiated_remotely{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - initiated remotely"
      }
     ]
    },
    {
     "title": "Handlers: Finished Exceptionally",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "cardano_handlers_finished_exceptionally_elapsed_time_microseconds_max{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - max"
      },
      {
       "expr": "cardano_handlers_finished_exceptionally_elapsed_time_microseconds_mean{role=\"[[role]]\"}",
       "legendFormat": "{{alias}} - mean"
      }
     ]
    },
    {
     "title": "BucketSubscription (non-stacked)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_queue_bucket_BucketSubscriptionListener{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "BucketSubscription (sum)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (cardano_queue_bucket_BucketSubscriptionListener{role=\"[[role]]\"})",
       "legendFormat": "sum all nodes"
      }
     ]
    },
    {
     "title": "Total Missed Blocks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cardano_current_global_slot - cardano_total_main_blocks{role=\"[[role]]\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "BucketSubscription (sum)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (cardano_queue_bucket_BucketSubscriptionListener)",
     "legendFormat": "sum all nodes"
    }
   ]
  }
 ]
}