{
 "title": "Byron-Reboot Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "TCP Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Frankfurt TCP connections",
   "type": "graph",
   "description": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE-WAIT",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{alias=~\"e-a-.*\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Tokyo TCP connections",
   "type": "graph",
   "description": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE-WAIT",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{alias=~\"e-b-.*\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Singapore TCP connections",
   "type": "graph",
   "description": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE-WAIT",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{alias=~\"e-c-.*\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Ohio TCP connections",
   "type": "graph",
   "description": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE-WAIT",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{alias=~\"e-d-.*\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "title": "Edge Node CPU% and Free Mem%", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Edge Node CPU Utilization (1m avg)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{alias=~\"e-.*\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Edge Node Memory Available (%)",
   "type": "graph",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{alias=~\"e-.*\"} / node_memory_MemTotal_bytes{alias=~\"e-.*\"} * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Edge Node Region Aggregate Bandwidth and BlockNum",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }
  },
  {
   "title": "Region Aggregate Bandwidth Comparison (bps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias=~\"e-a-.*\",device!~\"lo\"}[20s]) * -8)",
     "legendFormat": "Frankfurt Egress"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias=~\"e-b-.*\",device!~\"lo\"}[20s]) * -8)",
     "legendFormat": "Tokyo Egress"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias=~\"e-c-.*\",device!~\"lo\"}[20s]) * -8)",
     "legendFormat": "Singapore Egress"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias=~\"e-d-.*\",device!~\"lo\"}[20s]) * -8)",
     "legendFormat": "Ohio Egress"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=~\"e-a-.*\",device!~\"lo\"}[20s]) * 8)",
     "legendFormat": "Frankfurt Ingress"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=~\"e-b-.*\",device!~\"lo\"}[20s]) * 8)",
     "legendFormat": "Tokyo Ingress"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=~\"e-c-.*\",device!~\"lo\"}[20s]) * 8)",
     "legendFormat": "Singapore Ingress"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=~\"e-d-.*\",device!~\"lo\"}[20s]) * 8)",
     "legendFormat": "Ohio Ingress"
    }
   ]
  },
  {
   "title": "EdgeNode BlockNum",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_blockNum_int{alias=~\"e-.*\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "title": "Edge Node Egress Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Frankfurt Edge Node Egress Bandwidth (bps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{alias=~\"e-a-.*\",device!~\"lo\"}[20s]) * -8",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Tokyo Edge Node Egress Bandwidth (bps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{alias=~\"e-b-.*\",device!~\"lo\"}[20s]) * -8",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Singapore Edge Node Egress Bandwidth (bps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{alias=~\"e-c-.*\",device!~\"lo\"}[20s]) * -8",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Ohio Edge Node Egress Bandwidth (bps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{alias=~\"e-d-.*\",device!~\"lo\"}[20s]) * -8",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "title": "Edge Node Ingress Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Frankfurt Edge Node Ingress Bandwidth (bps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{alias=~\"e-a-.*\",device!~\"lo\"}[20s]) * 8",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Tokyo Edge Node Ingress Bandwidth (bps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{alias=~\"e-b-.*\",device!~\"lo\"}[20s]) * 8",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Singapore Edge Node Ingress Bandwidth (bps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{alias=~\"e-c-.*\",device!~\"lo\"}[20s]) * 8",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Ohio Edge Node Ingress Bandwidth (bps)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{alias=~\"e-d-.*\",device!~\"lo\"}[20s]) * 8",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}